### ISSUE TITLE
ets proxy install through the pip module

### ISSUE THREAD

**Issue by allamiro** [enthought/etsproxy#1]
etsproxy install through the pip module is not available recommending this as a feature request

**Comment by mdickinson** [comment]
Hi @allamiro. The etsproxy package is no longer maintained, and all other Enthought Tool Suite projects have long since moved away from using etsproxy. Did you have find a place where etsproxy was still needed?

**Comment by mdickinson** [comment]
I'm going to close this issue. If you find another project that's using etsproxy, please do open an issue against that project's issue tracker. I've also opened a PR (#2) to update the README to make it clearer that etsproxy is defunct.
